Resources:
    ApiGatewayStage:
        Type: 'AWS::ApiGateway::Stage'
        Properties:
            StageName: ${self:provider.stage}
            DeploymentId:
                Ref: __deployment__
            RestApiId:
                Ref: ApiGatewayRestApi
            MethodSettings:
                -
                    ResourcePath: /*
                    HttpMethod: '*'
                    LoggingLevel: INFO
                    DataTraceEnabled: true
                    MetricsEnabled: true
    ApiGatewayBasePathMapping:
        Type: 'AWS::ApiGateway::BasePathMapping'
        Properties:
            BasePath: ${self:app}-${self:service}
            DomainName: '${self:provider.stage}-api.zeconomy.com'
            RestApiId:
                Ref: ApiGatewayRestApi
            Stage:
                Ref: ApiGatewayStage
