Resources:
    Employees:
        Type: 'AWS::DynamoDB::Table'
        Properties:
            TableName: ${self:provider.stackTags.name}-translations
            BillingMode: PAY_PER_REQUEST
            PointInTimeRecoverySpecification:
                PointInTimeRecoveryEnabled: true
            AttributeDefinitions:
                -
                    AttributeName: english
                    AttributeType: S
                -
                    AttributeName: spanish
                    AttributeType: S
            KeySchema:
                -
                    AttributeName: english
                    KeyType: HASH
            GlobalSecondaryIndexes:
                -
                    IndexName: spanish
                    KeySchema:
                        -
                            AttributeName: spanish
                            KeyType: HASH
                    Projection:
                        ProjectionType: ALL
