environment:
    BASE_PATH: ${self:app}-${self:service}
    STACK: ${self:provider.stackTags.name}
    STAGE: ${self:provider.stage}
    DYNAMODB_ENDPOINT: http://localhost:4000
    DYNAMODB_TRANSLATIONS: ${self:provider.stackTags.name}-translations
